language: node_js
node_js:
  - '12'
services:
  - postgresql
before_script:
  - psql -c 'create database soundhub;' -U postgres
script:
  - cd back
  - mkdir public
  - cd public
  - mkdir sounds
  - cd sounds
  - pwd
  - ls
  - cd ..
  - cd ..
  - npm install
  - npm start &
deploy:
  provider: heroku
  api_key: $APIKEYHEROKU
  app: soundhubback