language: node_js
node_js:
  - '12'
script:
  - npm install
  - npm start
deploy:
  provider: heroku
  api_key: $APIKEYHEROKU
  app: soundhub
on:
    branch: master
    tags: true
    repo: soundhub/back