language: node_js
node_js:
  - '12'
script:
  - cd back
  - mkdir public
  - cd public
  - mkdir sounds
  - cd ..
  - npm install
  - npm start &
deploy:
  provider: heroku
  api_key: $APIKEYHEROKU
  app: soundhubback