version: "3.5"
services:

  frontend:
    container_name: frontend_soundhub
    build: 
      dockerfile: Dockerfile
      context: ./front
    volumes:
      - ./front:/usr/src/front-app
      - ./front/package.json:/usr/src/front-app/package.json
      - /usr/src/front-app/node_modules
    ports:
      - "9093:9093"
    networks:
      - network_soundhub

  backend:
    container_name: backend_soundhub
    build: 
      dockerfile: Dockerfile
      context: ./back
    volumes:
      - ./back:/usr/src/back-app
      - ./back/package.json:/usr/src/back-app/package.json
      - /usr/src/back-app/node_modules
    ports:
      - "8003:8003"
    networks:
      - network_soundhub

networks:
  network_soundhub: {}